language: emacs-lisp
sudo: false
env:
  matrix:
    - EMACS_BINARY=emacs-24.4-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-24.4-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-24.5-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-24.5-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.2-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.2-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-25.3-travis MAKE_TEST=test-checks
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-26-pretest-travis MAKE_TEST=test-checks
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test-bytecomp
    - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test-checks
before_script:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EMACS_BINARY --use --skip
  - cask
script:
  - emacs --version
  - cask install
  - cask exec buttercup -L .
